import React from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { PageHeader } from '../../components/common/PageHeader';
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from '../../components/ui/Card';
import { Button } from '../../components/ui/Button';
import { Badge } from '../../components/ui/Badge';
import { ScoreChart } from '../../components/charts/ScoreChart';
import { ArrowLeft, Sparkles } from 'lucide-react';

export const InterviewResultPage = () => {
  const { id } = useParams();
  const navigate = useNavigate();

  return (
    <div className="space-y-6 max-w-4xl mx-auto">
      <PageHeader
        title={`Interview Result & AI Feedback (Session: ${id})`}
        description="Comprehensive evaluation generated by Gemini AI."
        action={
          <Button variant="outline" size="sm" onClick={() => navigate('/interviews')} leftIcon={<ArrowLeft className="w-4 h-4" />}>
            Back to Interviews
          </Button>
        }
      />

      <Card variant="glass">
        <CardHeader>
          <div className="flex items-center justify-between">
            <CardTitle>Overall Performance Score</CardTitle>
            <Badge variant="success" size="md">Passed Technical Bar</Badge>
          </div>
          <CardDescription>Multi-dimensional score breakdown across 5 technical categories.</CardDescription>
        </CardHeader>
        <CardContent className="space-y-6">
          <ScoreChart />
          <div className="p-4 rounded-xl bg-slate-900/60 border border-slate-800 text-xs text-slate-300 leading-relaxed">
            <h4 className="font-semibold text-indigo-300 mb-1 flex items-center gap-1.5">
              <Sparkles className="w-3.5 h-3.5" /> Gemini Key Recommendation:
            </h4>
            "Strong system design principles. To improve further, practice specifying exact SLA/SLO latency numbers and Redis eviction strategies during database sharding scenarios."
          </div>
        </CardContent>
      </Card>
    </div>
  );
};

export default InterviewResultPage;
