import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import {
  Compass,
  Sparkles,
  RefreshCw,
  CheckCircle2,
  Circle,
  Clock,
  BookOpen,
  Target,
  ArrowRight,
  Layers,
  Award,
  Check
} from 'lucide-react';
import { PageHeader } from '../../components/common/PageHeader';
import { Button } from '../../components/ui/Button';
import { Badge } from '../../components/ui/Badge';
import { ProgressBar } from '../../components/ui/ProgressBar';
import { SkeletonCard } from '../../components/ui/LoadingState';
import { ErrorState } from '../../components/ui/ErrorState';
import { EmptyState } from '../../components/ui/EmptyState';
import { useActiveRoadmap } from '../../hooks/useActiveRoadmap';
import { roadmapService } from '../../services/roadmapService';
import { GenerateRoadmapModal } from '../../components/roadmap/GenerateRoadmapModal';
import { RoadmapPhaseTimeline } from '../../components/roadmap/RoadmapPhaseTimeline';
import { RoadmapProgressTracker } from '../../components/roadmap/RoadmapProgressTracker';

import { useToast } from '../../hooks/useToast';

export const RoadmapPage = () => {
  const navigate = useNavigate();
  const toast = useToast();
  const { roadmap, tasks, progress, loading, error, refresh } = useActiveRoadmap();

  // Generate Roadmap Modal State
  const [showGenerateModal, setShowGenerateModal] = useState(false);

  // Milestone Toast State
  const [milestoneMessage, setMilestoneMessage] = useState(null);

  // Task Status Update State
  const [updatingTaskId, setUpdatingTaskId] = useState(null);

  // Open Generate Modal
  const handleOpenGenerateModal = () => {
    setShowGenerateModal(true);
  };

  // Task Complete Action Handler
  const handleCompleteTask = async (taskId) => {
    if (!taskId || updatingTaskId) return;

    setUpdatingTaskId(taskId);
    setMilestoneMessage(null);

    try {
      const response = await roadmapService.completeTask(taskId);
      const resData = response?.data || response;
      const progressInfo = resData?.progress || {};

      let msg = 'Task marked as completed!';
      if (progressInfo.roadmapProgress === 100 || progressInfo.roadmapStatus === 'COMPLETED') {
        msg = '🎉 Congratulations! You have completed your entire AI Learning Roadmap!';
        toast.custom('Roadmap Completed!', msg);
      } else if (progressInfo.phaseProgress === 100 || progressInfo.phaseStatus === 'COMPLETED') {
        msg = '🌟 Phase Milestone Achieved! You completed all tasks in this phase.';
        toast.success('Phase Completed!', msg);
      } else if (progressInfo.roadmapProgress >= 50 && progress < 50) {
        msg = '🚀 Halfway Milestone! You crossed 50% overall roadmap completion.';
        toast.info('Halfway Milestone!', msg);
      } else {
        toast.success('Task Completed', 'Roadmap progress updated.');
      }
      setMilestoneMessage(msg);

      await refresh();
    } catch (err) {
      toast.error('Task Update Failed', 'Failed to mark task as completed.');
    } finally {
      setUpdatingTaskId(null);
    }
  };

  if (loading && !roadmap) {
    return (
      <div className="space-y-6 max-w-5xl mx-auto pb-16">
        <div className="w-full h-24 rounded-2xl animate-pulse bg-slate-900/80 border border-slate-800" />
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          <SkeletonCard />
          <SkeletonCard className="lg:col-span-2" />
        </div>
      </div>
    );
  }

  if (error && !roadmap) {
    return (
      <div className="py-12 max-w-3xl mx-auto space-y-6">
        <ErrorState
          title="Learning Roadmap Unavailable"
          message={error}
          onRetry={refresh}
        />
      </div>
    );
  }

  // Handle No Active Roadmap State
  if (!roadmap) {
    return (
      <div className="space-y-8 max-w-5xl mx-auto pb-16">
        <PageHeader
          title="Your AI Career Roadmap"
          description="Tailored technical milestones and task progression generated by Gemini AI to eliminate candidate skill gaps."
        />

        <EmptyState
          icon={<Sparkles className="w-12 h-12 text-indigo-400" />}
          title="No Active Learning Roadmap"
          description="Generate your personalized AI learning roadmap tailored to your target engineering role."
          primaryAction={{
            label: 'Generate AI Roadmap',
            icon: <Sparkles className="w-4 h-4" />,
            onClick: handleOpenGenerateModal,
          }}
        />

        {/* Generate Modal */}
        <GenerateRoadmapModal
          isOpen={showGenerateModal}
          onClose={() => setShowGenerateModal(false)}
          onSuccess={() => refresh()}
          activeRoadmap={null}
        />
      </div>
    );
  }

  // Derived Active Roadmap Details
  const title = roadmap.title || 'Learning Roadmap';
  const description = roadmap.description || 'Structured candidate learning roadmap generated by AI.';
  const targetRole = roadmap.targetRole || 'Software Engineer';
  const overallProgress = progress ?? roadmap.overallProgress ?? 0;
  const status = roadmap.status || 'ACTIVE';
  const phases = roadmap.phases || [];

  // Task Statistics
  const completedTasksCount = tasks.filter((t) => t.status === 'COMPLETED' || t.status === 'Completed' || t.status === 'SKIPPED').length;
  const totalTasksCount = tasks.length;

  // Active Focus Phase & Next Recommended Task
  const currentPhase = phases.find((p) => p.status !== 'COMPLETED' && p.progress < 100) || phases[0] || null;
  const currentFocus = currentPhase?.title || 'Core Foundation';
  const currentPhaseProgress = currentPhase?.progress || 0;

  const nextRecommendedTask =
    tasks.find((t) => t.status === 'IN_PROGRESS' || t.status === 'In Progress') ||
    tasks.find((t) => t.status === 'PENDING' || t.status === 'Not Started' || t.status === 'NOT_STARTED') ||
    tasks[0] || null;

  return (
    <div className="space-y-8 max-w-5xl mx-auto pb-16">
      
      {/* Header & Control Actions */}
      <PageHeader
        title="Your AI Career Roadmap"
        description="Tailored technical milestones and task progression generated by Gemini AI to eliminate candidate skill gaps."
        action={
          <div className="flex items-center gap-3">
            <Button
              variant="outline"
              size="sm"
              onClick={refresh}
              isLoading={loading}
              leftIcon={<RefreshCw className="w-3.5 h-3.5" />}
            >
              Refresh
            </Button>
            <Button
              variant="primary"
              size="sm"
              onClick={handleOpenGenerateModal}
              leftIcon={<Sparkles className="w-4 h-4" />}
            >
              Generate New Roadmap
            </Button>
          </div>
        }
      />

      {/* Real-time Progress Metrics & Milestone Banner */}
      <RoadmapProgressTracker
        overallProgress={overallProgress}
        currentPhaseProgress={currentPhaseProgress}
        currentPhaseTitle={currentFocus}
        completedTasks={completedTasksCount}
        totalTasks={totalTasksCount}
        roadmapStatus={status}
        milestoneMessage={milestoneMessage}
        onDismissMilestone={() => setMilestoneMessage(null)}
      />

      {/* Hero Progress Overview Card */}
      <div className="bg-slate-900/80 border border-slate-800 rounded-3xl p-6 sm:p-8 backdrop-blur-xl shadow-2xl space-y-6 relative overflow-hidden">
        
        {/* Glow Accent */}
        <div className="absolute -top-24 -right-24 w-80 h-80 bg-indigo-500/10 rounded-full blur-3xl pointer-events-none" />

        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-6 border-b border-slate-800/80 pb-6">
          <div className="space-y-2">
            <div className="flex items-center gap-2.5">
              <span className="text-[11px] font-bold uppercase tracking-wider text-indigo-400 bg-indigo-500/10 border border-indigo-500/20 px-3 py-1 rounded-full flex items-center gap-1.5">
                <Compass className="w-3.5 h-3.5" /> Active Career Roadmap
              </span>
              <Badge variant="success" size="sm" icon={<Target className="w-3.5 h-3.5" />}>
                {targetRole}
              </Badge>
              <Badge variant="outline" size="sm">
                {status}
              </Badge>
            </div>
            <h1 className="text-2xl sm:text-3xl font-extrabold text-white tracking-tight">
              {title}
            </h1>
            <p className="text-xs sm:text-sm text-slate-400 max-w-2xl leading-relaxed">
              {description}
            </p>
          </div>

          {/* Hero Progress Circle */}
          <div className="flex items-center gap-4 bg-slate-950/60 border border-slate-800 p-4 rounded-2xl shrink-0">
            <div className="w-20 h-20 rounded-2xl bg-indigo-500/10 border border-indigo-500/30 flex flex-col items-center justify-center text-indigo-400">
              <span className="text-3xl font-black">{overallProgress}%</span>
              <span className="text-[9px] uppercase font-bold text-indigo-300/80">Complete</span>
            </div>
          </div>
        </div>

        {/* Progress Bar Component */}
        <ProgressBar
          value={overallProgress}
          max={100}
          showPercentage={false}
          color="indigo"
          size="lg"
        />

        {/* Stat Metrics Bar */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 pt-2">
          <div className="p-3.5 rounded-2xl bg-slate-950/50 border border-slate-800 space-y-1">
            <span className="text-[11px] text-slate-400 font-semibold flex items-center gap-1.5">
              <Layers className="w-3.5 h-3.5 text-indigo-400" /> Total Phases
            </span>
            <span className="text-lg font-bold text-white block">{phases.length} Phases</span>
          </div>

          <div className="p-3.5 rounded-2xl bg-slate-950/50 border border-slate-800 space-y-1">
            <span className="text-[11px] text-slate-400 font-semibold flex items-center gap-1.5">
              <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400" /> Completed Tasks
            </span>
            <span className="text-lg font-bold text-emerald-400 block">{completedTasksCount}</span>
          </div>

          <div className="p-3.5 rounded-2xl bg-slate-950/50 border border-slate-800 space-y-1">
            <span className="text-[11px] text-slate-400 font-semibold flex items-center gap-1.5">
              <Circle className="w-3.5 h-3.5 text-amber-400" /> Tasks Remaining
            </span>
            <span className="text-lg font-bold text-amber-400 block">{totalTasksCount - completedTasksCount}</span>
          </div>

          <div className="p-3.5 rounded-2xl bg-slate-950/50 border border-slate-800 space-y-1">
            <span className="text-[11px] text-slate-400 font-semibold flex items-center gap-1.5">
              <Award className="w-3.5 h-3.5 text-cyan-400" /> Roadmap Status
            </span>
            <span className="text-lg font-bold text-cyan-300 block">{status}</span>
          </div>
        </div>

      </div>

      {/* Current Focus & Next Recommended Task Card */}
      {nextRecommendedTask && (
        <div className="bg-slate-900/80 border border-slate-800 rounded-3xl p-6 sm:p-8 backdrop-blur-xl shadow-2xl space-y-6">
          <div className="flex items-center justify-between border-b border-slate-800/80 pb-4">
            <div>
              <span className="text-[11px] font-bold uppercase tracking-wider text-indigo-400 flex items-center gap-1.5 mb-1">
                <BookOpen className="w-4 h-4" /> Current Focus
              </span>
              <h3 className="text-lg font-extrabold text-white">
                {currentFocus}
              </h3>
            </div>
            <Badge variant="primary" size="sm">
              Recommended Next Action
            </Badge>
          </div>

          <div className="p-5 rounded-2xl bg-slate-950/80 border border-slate-800 space-y-3">
            <div className="flex items-center justify-between gap-2">
              <span className="text-xs font-bold text-indigo-300 uppercase tracking-wider">
                Next Task
              </span>
              <span className="text-xs text-slate-400 flex items-center gap-1">
                <Clock className="w-3.5 h-3.5 text-cyan-400" /> ~{nextRecommendedTask.estimatedMinutes || 45} mins
              </span>
            </div>

            <h4 className="text-base font-bold text-white">
              "{nextRecommendedTask.title}"
            </h4>

            <p className="text-xs text-slate-400 leading-relaxed">
              {nextRecommendedTask.description || 'Complete this task to progress your roadmap milestone.'}
            </p>
          </div>

          <div className="flex justify-end pt-2">
            <Button
              variant="primary"
              size="md"
              onClick={() => handleCompleteTask(nextRecommendedTask._id || nextRecommendedTask.id)}
              isLoading={updatingTaskId === (nextRecommendedTask._id || nextRecommendedTask.id)}
              leftIcon={<Check className="w-4 h-4" />}
              rightIcon={<ArrowRight className="w-4 h-4" />}
              className="px-8 shadow-indigo-500/20"
            >
              Continue Learning
            </Button>
          </div>
        </div>
      )}

      {/* Roadmap Phases Visual Node Timeline */}
      <div className="bg-slate-900/80 border border-slate-800 rounded-3xl p-6 sm:p-8 backdrop-blur-xl shadow-2xl">
        <RoadmapPhaseTimeline
          phases={phases}
          tasks={tasks}
        />
      </div>

      {/* Generate AI Roadmap Modal */}
      <GenerateRoadmapModal
        isOpen={showGenerateModal}
        onClose={() => setShowGenerateModal(false)}
        onSuccess={() => refresh()}
        activeRoadmap={roadmap}
      />

    </div>
  );
};

export default RoadmapPage;
