import React from 'react';
import { PageHeader } from '../../components/common/PageHeader';
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from '../../components/ui/Card';
import { Badge } from '../../components/ui/Badge';
import { CheckCircle2, Circle } from 'lucide-react';

export const RoadmapPage = () => {
  return (
    <div className="space-y-6">
      <PageHeader
        title="Personalized Learning Roadmap"
        description="Tailored technical milestones generated by Gemini AI to address your specific interview skill gaps."
      />

      <Card variant="glass">
        <CardHeader>
          <CardTitle>Milestone Milestones</CardTitle>
          <CardDescription>Target Role: Senior Full Stack Engineer</CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="p-4 rounded-xl bg-slate-900/60 border border-slate-800 flex items-center justify-between">
            <div className="flex items-center gap-3">
              <CheckCircle2 className="w-5 h-5 text-emerald-400 shrink-0" />
              <div>
                <h4 className="text-sm font-semibold text-slate-200">Phase 1: React 19 Concurrent Features</h4>
                <p className="text-xs text-slate-400">useActionState, useOptimistic, and Server Components</p>
              </div>
            </div>
            <Badge variant="success" size="sm">Completed</Badge>
          </div>

          <div className="p-4 rounded-xl bg-slate-900/60 border border-slate-800 flex items-center justify-between">
            <div className="flex items-center gap-3">
              <Circle className="w-5 h-5 text-indigo-400 shrink-0 animate-pulse" />
              <div>
                <h4 className="text-sm font-semibold text-slate-200">Phase 2: Distributed Caching & Redis</h4>
                <p className="text-xs text-slate-400">Cache invalidation patterns & pub/sub messaging</p>
              </div>
            </div>
            <Badge variant="primary" size="sm">In Progress</Badge>
          </div>
        </CardContent>
      </Card>
    </div>
  );
};

export default RoadmapPage;
