import React from 'react';
import { PageHeader } from '../../components/common/PageHeader';
import { Button } from '../../components/ui/Button';
import { SkeletonCard } from '../../components/ui/LoadingState';
import { ErrorState } from '../../components/ui/ErrorState';
import { Sparkles, RefreshCw } from 'lucide-react';
import { useActiveRoadmap } from '../../hooks/useActiveRoadmap';
import { RoadmapProgressCard, CurrentLearningTask } from '../../components/roadmap';

export const RoadmapPage = () => {
  const { roadmap, tasks, progress, loading, error, refresh } = useActiveRoadmap();

  if (loading && !roadmap) {
    return (
      <div className="space-y-6">
        <div className="w-full h-24 rounded-2xl animate-pulse bg-slate-900/80 border border-slate-800" />
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          <SkeletonCard />
          <SkeletonCard />
        </div>
      </div>
    );
  }

  if (error && !roadmap) {
    return (
      <div className="py-8">
        <ErrorState
          title="Learning Roadmap Unavailable"
          message={error}
          onRetry={refresh}
        />
      </div>
    );
  }

  return (
    <div className="space-y-6 sm:space-y-8 pb-10">
      <PageHeader
        title="Personalized AI Learning Roadmap"
        description="Tailored technical milestones and task progression generated by Gemini AI to eliminate candidate skill gaps."
        action={
          <div className="flex items-center gap-3">
            <Button
              variant="outline"
              size="sm"
              onClick={refresh}
              isLoading={loading}
              leftIcon={<RefreshCw className="w-3.5 h-3.5" />}
            >
              Refresh Roadmap
            </Button>
          </div>
        }
      />

      {/* Grid: RoadmapProgressCard & CurrentLearningTask */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <div className="flex">
          <RoadmapProgressCard
            roadmap={roadmap}
            tasks={tasks}
            progress={progress}
          />
        </div>

        {roadmap && (
          <div className="flex">
            <CurrentLearningTask
              roadmap={roadmap}
              tasks={tasks}
            />
          </div>
        )}
      </div>
    </div>
  );
};

export default RoadmapPage;
